import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://loanformulas.com";

  const routes = [
  
    "/about",
    "/contact",
    "/privacy-policy",
    "/terms-of-service",
    "/sitemap-page",
    "/mortgage-calculator",
    "/refinance-calculator",
    "/affordability-calculator",
    "/down-payment-calculator",
    "/rent-vs-buy-calculator",
    "/extra-payment-calculator",
    "/biweekly-mortgage-calculator",
    "/mortgage-payoff-calculator",
    "/mortgage-interest-calculator",
    "/mortgage-points-calculator",
    "/mortgage-insurance-calculator",
    "/property-tax-calculator",
    "/home-equity-calculator",
    "/home-equity-loan-calculator",
    "/home-equity-line-of-credit-calculator",
    "/heloc-calculator",
    "/closing-cost-calculator",
    "/house-payment-calculator",
    "/home-affordability-calculator",
    "/real-estate-calculator",
    "/cash-out-refinance-calculator",
    "/adjustable-rate-mortgage-calculator",
    "/arm-calculator",
    "/principal-and-interest-calculator",
    "/escrow-calculator",
    "/mortgage-amortization-calculator",
    "/auto-loan-calculator",
    "/car-payment-calculator",
    "/car-affordability-calculator",
    "/lease-calculator",
    "/car-lease-calculator",
    "/used-car-calculator",
    "/vehicle-loan-calculator",
    "/trade-in-calculator",
    "/auto-refinance-calculator",
    "/gas-cost-calculator",
    "/fuel-cost-calculator",
    "/ev-savings-calculator",
    "/vehicle-depreciation-calculator",
    "/loan-calculator",
    "/personal-loan-calculator",
    "/payday-loan-calculator",
    "/student-loan-calculator",
    "/student-loan-payoff-calculator",
    "/student-loan-refinance-calculator",
    "/interest-payoff-calculator",
    "/loan-payoff-calculator",
    "/line-of-credit-calculator",
    "/balance-transfer-calculator",
    "/debt-consolidation-calculator",
    "/credit-card-payoff-calculator",
    "/debt-snowball-calculator",
    "/debt-avalanche-calculator",
    "/minimum-payment-calculator",
    "/debt-payoff-calculator",
    "/credit-utilization-calculator",
    "/compound-interest-calculator",
    "/apr-calculator",
    "/apy-calculator",
    "/simple-interest-calculator",
    "/investment-return-calculator",
    "/annual-return-calculator",
    "/future-value-calculator",
    "/present-value-calculator",
    "/inflation-calculator",
    "/real-return-calculator",
    "/risk-reward-calculator",
    "/investment-calculator",
    "/dividend-calculator",
    "/stock-calculator",
    "/etf-calculator",
    "/mutual-fund-calculator",
    "/portfolio-calculator",
    "/capital-gains-calculator",
    "/roi-calculator",
    "/retirement-calculator",
    "/savings-calculator",
    "/net-worth-calculator",
    "/wealth-calculator",
    "/financial-independence-calculator",
    "/fire-calculator",
    "/certificate-of-deposit-calculator",
    "/amortization-calculator",
    "/high-yield-savings-calculator",
    "/emergency-fund-calculator",
    "/bank-interest-calculator",
    "/recurring-deposit-calculator",
    "/budget-calculator",
    "/expense-calculator",
    "/cash-flow-calculator",
    "/monthly-budget-calculator",
    "/weekly-savings-calculator",
    "/401k-calculator",
    "/roth-ira-calculator",
    "/ira-calculator",
    "/pension-calculator",
    "/social-security-calculator",
    "/retirement-savings-calculator",
    "/retirement-income-calculator",
    "/retirement-withdrawal-calculator",
    "/early-retirement-calculator",
    "/salary-calculator",
    "/hourly-wage-calculator",
    "/take-home-pay-calculator",
    "/tax-calculator",
    "/income-tax-calculator",
    "/bonus-tax-calculator",
    "/overtime-calculator",
    "/commission-calculator",
    "/freelance-tax-calculator",
    "/self-employment-tax-calculator",
    "/paycheck-calculator",

  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "daily" : "weekly",
    priority: route === "" ? 1.0 : 0.85,
  }));
}